<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use HasFactory;
	protected $fillable = [
    'order_no',
    'source',
    'channel',
	'invoice_no',
	'invoice_amount',
	'courrier_id',
	'omnee_order',
	'order_type',
	'shipment_mode',
	'business_account',
	'client_code',
	'gst_no',
	'currency_code',
	'consignment_type',
	'shipping_label',
	'manifest_url',
	'invoice_url',
	'payment_mode',
	'total_quantity',
	'shipping_charges',
	'total_amount',
	'cod_amount',
	'discount_amount',
	'tax_amount',
	'invoice_no',
	'invoice_amount',
	'no_of_invoice',
	'invoice_date',
	'no_of_box',
	'awb_no',
	'dimension_unit',
	'height',
	'length',
	'breadth',
	'weight_unit',
	'total_weight',
	'volumetric_weight',
	'vol_weight',
	'length',
	'breadth',
	'height',
	'courier_name',
	'courrier_id',
	'shipping_first_name',
	'shipping_company_name',
	'shipping_address_1',
	'shipping_address_2',
	'shipping_phone_number',
	'shipping_alternate_phone',
	'shipping_email',
	'shipping_city',
	'shipping_state',
	'shipping_country',
	'shipping_pincode',
	'billing_first_name',
	'billing_company_name',
	'billing_address_1',
	'billing_address_2',
	'billing_phone_number',
	'billing_alternate_phone',
	'billing_email',
	'billing_city',
	'billing_state',
	'billing_country',
	'billing_pincode',
	'latitude',
	'longitude',
	'hyperlocal_address',
	'postal_code',
	'warehouse_name',
	'warehouse_code',
	'warehouse_address',
	'warehouse_address_2',
	'warehouse_state',
	'warehouse_city',
	'warehouse_pincode',
	'warehouse_phone_number',
	'warehouse_alternate_phone',
	'remarks',
	'tracking_history',
	'order_status',
	'status',
	'sending_status',
	'order_request',
	'request_partner',
   ];
}
